###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################

mydockerphp-webserver:
  image: phpdockerio/nginx:latest
  container_name: mydockerphp-webserver
  volumes:
      - ..:/var/www/mydockerphp
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  ports:
   - "35003:80"
  links:
   - mydockerphp-php-fpm

mydockerphp-php-fpm:
  build: .
  dockerfile: php-fpm/Dockerfile
  container_name: mydockerphp-php-fpm
  volumes:
    - ..:/var/www/mydockerphp
    - ./php-fpm/php-ini-overrides.ini:/etc/php5/fpm/conf.d/99-overrides.ini
